apiVersion: v1
kind: Namespace
metadata:
  name: prometheus-system
  labels:
    istio.io/dataplane-mode: ambient
---
apiVersion: v1
kind: Namespace
metadata:
  name: loki-system
  labels:
    istio.io/dataplane-mode: ambient
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: loki-system
  labels:
    istio.io/global: "true"
spec:
  selector:
    app: loki
  ports:
    - name: http
      port: 3100
      targetPort: 3100
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: prometheus-system
  labels:
    istio.io/global: "true"
spec:
  selector:
    app: prometheus
  ports:
    - name: http
      port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-c
  labels:
    istio.io/dataplane-mode: ambient
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl
  namespace: ns-c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl
  template:
    metadata:
      labels:
        app: curl
    spec:
      containers:
        - name: curl
          image: curlimages/curl:8.6.0
          command: ["sleep", "365d"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: ns-c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:11.0.0
          ports:
            - containerPort: 3000
          env:
            # Enable anonymous access (no login)
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: "Admin"

            # Disable login form entirely
            - name: GF_AUTH_DISABLE_LOGIN_FORM
              value: "true"

            # Auto-provision Prometheus + Loki datasources
            - name: GF_DATASOURCES_DEFAULT
              value: "prometheus"

            - name: GF_PROVISIONING_PATH
              value: /etc/grafana/provisioning

          volumeMounts:
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources

      volumes:
        - name: grafana-datasources
          configMap:
            name: grafana-datasources
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: ns-c
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.prometheus-system.svc.cluster.local:9090
        isDefault: true

      - name: Loki
        type: loki
        access: proxy
        url: http://loki.loki-system.svc.cluster.local:3100