apiVersion: v1
kind: Namespace
metadata:
  name: prometheus-system
  labels:
    istio.io/dataplane-mode: ambient
---
apiVersion: v1
kind: Namespace
metadata:
  name: loki-system
  labels:
    istio.io/dataplane-mode: ambient
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: loki-system
  labels:
    istio.io/global: "true"
spec:
  selector:
    app: loki
  ports:
    - name: http
      port: 3100
      targetPort: 3100
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: prometheus-system
  labels:
    istio.io/global: "true"
spec:
  selector:
    app: prometheus
  ports:
    - name: http
      port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-c
  labels:
    istio.io/dataplane-mode: ambient
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl
  namespace: ns-c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl
  template:
    metadata:
      labels:
        app: curl
    spec:
      containers:
        - name: curl
          image: curlimages/curl:8.6.0
          command: ["sleep", "365d"]