apiVersion: v1
kind: Namespace
metadata:
  name: prometheus-system
  labels:
    istio.io/dataplane-mode: ambient
---
apiVersion: v1
kind: Namespace
metadata:
  name: loki-system
  labels:
    istio.io/dataplane-mode: ambient
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: loki-system
  labels:
    istio.io/global: "true"
spec:
  selector:
    app: loki
  ports:
    - name: http
      port: 3100
      targetPort: 3100
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: prometheus-system
  labels:
    istio.io/global: "true"
spec:
  selector:
    app: prometheus
  ports:
    - name: http
      port: 9090
      targetPort: 9090
