apiVersion: v1
kind: Namespace
metadata:
  name: ns-a
  labels:
    istio.io/dataplane-mode: ambient
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-b
  labels:
    istio.io/dataplane-mode: ambient
---
apiVersion: v1
kind: Service
metadata:
  name: service-a
  namespace: ns-a
  labels:
    istio.io/global: "true"
spec:
  selector:
    app: nginx-a
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-b
  namespace: ns-b
  labels:
    istio.io/global: "true"
spec:
  selector:
    app: nginx-b
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-c
  labels:
    istio.io/dataplane-mode: ambient
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl
  namespace: ns-c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl
  template:
    metadata:
      labels:
        app: curl
    spec:
      containers:
        - name: curl
          image: curlimages/curl:8.6.0
          command: ["sleep", "365d"]
